coverage:
  status:
    project:
      default:
        target: 65%
    patch: off
ignore:
  - "datasource/gcp.go"
  - "drivers/bq"
  - "drivers/spanner"
  - "schema/json.go"
  - "schema/yaml.go"
  - "internal/*"
