run: 
  timeout: 5m
linters:
  fast: false
  enable:
    - misspell
    - gosec
linters-settings:
  errcheck:
    check-type-assertions: true
  staticcheck:
    go: "1.21"
  misspell:
    locale: US
    ignore-words: []
issues:
  exclude:
    - SA3000
