before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: tbls-darwin
  hooks:
    pre: packr2
    post: packr2 clean
  ldflags:
    - -s -w -X github.com/k1LoW/tbls.version={{.Version}} -X github.com/k1LoW/tbls.commit={{.FullCommit}} -X github.com/k1LoW/tbls.date={{.Date}} -X github.com/k1LoW/tbls/version.Version={{.Version}}
  env:
    - CGO_ENABLED=1
  goos:
    - darwin
  goarch:
    - amd64
-
  id: tbls-linux
  hooks:
    pre: packr2
    post: packr2 clean
  ldflags:
    - -s -w -X github.com/k1LoW/tbls.version={{.Version}} -X github.com/k1LoW/tbls.commit={{.FullCommit}} -X github.com/k1LoW/tbls.date={{.Date}} -X github.com/k1LoW/tbls/version.Version={{.Version}}
    - -linkmode external
    - -extldflags '-static'
  env:
    - CGO_ENABLED=1
    - CC=/usr/local/bin/x86_64-linux-musl-cc
  goos:
    - linux
  goarch:
    - amd64
-
  id: tbls-windows
  hooks:
    pre: packr2
    post: packr2 clean
  ldflags:
    - -s -w -X github.com/k1LoW/tbls.version={{.Version}} -X github.com/k1LoW/tbls.commit={{.FullCommit}} -X github.com/k1LoW/tbls.date={{.Date}} -X github.com/k1LoW/tbls/version.Version={{.Version}}
    - -extldflags '-static'
  env:
    - CGO_ENABLED=1
    - CC=x86_64-w64-mingw32-gcc
  goos:
    - windows
  goarch:
    - amd64
archives:
-
  id: tbls-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
-
  name: tbls
  github:
    owner: k1LoW
    name: homebrew-tap
  commit_author:
    name: k1LoW
    email: k1lowxb@gmail.com
  homepage: https://github.com/k1LoW/tbls
  description: 'tbls is a CI-Friendly tool for document a database, written in Go.'
  install: bin.install 'tbls'
nfpms:
  -
    id: tbls-nfpms
    name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
    - tbls-linux
    homepage: https://github.com/k1LoW/tbls
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: tbls is a CI-Friendly tool for document a database, written in Go.
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
