language: go
go:
  - 1.11.x
  - 1.12.x
  - master
env: GO111MODULE=on
services:
  - docker
dist: xenial
addons:
  apt:
    update: true
before_install:
  - test "$TRAVIS_BRANCH" = 'master' && openssl aes-256-cbc -K $encrypted_41d865494e68_key -iv $encrypted_41d865494e68_iv
    -in client_secrets.json.enc -out client_secrets.json -d
install:
  - echo $TRAVIS_GO_VERSION
  - sudo pip install codecov
  - make depsdev
  - docker-compose up -d
  - sleep 20s
script:
  - make ci
  - test "$TRAVIS_BRANCH" = 'master' && make test_bigquery
after_script:
  - codecov
