version: '3.4'

services:
  postgres:
    image: postgres:10
    restart: always
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=testdb
  mysql:
    image: mysql:5.6
    restart: always
    ports:
      - "33306:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  mysql8:
    image: mysql:8
    restart: always
    ports:
      - "33308:3306"
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=mypass
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    ports:
      - "11433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MSSQLServer-Passw0rd
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "18000:8000"
