name: build

on: push

jobs:
  linux-test:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go_version: [1.13, 1.14]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go ${{ matrix.go_version }} on ${{ matrix.platform }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install sqlite3
          sudo pip install codecov

      - name: Install aws-cli
        uses: chrislennon/action-aws-cli@v1.1

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Decrypt secrets
        run: gpg --quiet --batch --yes --decrypt --passphrase="$GCP_CLIENT_SECRETS_PASSPHRASE" --output $GITHUB_WORKSPACE/client_secrets.json $GITHUB_WORKSPACE/client_secrets.json.gpg
        if: github.ref == 'refs/heads/master'
        env:
          GCP_CLIENT_SECRETS_PASSPHRASE: ${{ secrets.GCP_CLIENT_SECRETS_PASSPHRASE }}

      - name: Start databases
        run: |
          docker-compose up -d
          sleep 20s

      - name: Run tests
        run: env PATH=`go env GOPATH`/bin:$PATH make ci
        env:
          DEBUG: "true"
          GOPROXY: "https://proxy.golang.org"

      - name: Run BigQuery integration
        run: env PATH=`go env GOPATH`/bin:$PATH make test_bigquery
        if: github.ref == 'refs/heads/master'
        env:
          GOPROXY: "https://proxy.golang.org"

      - name: Run codecov
        run: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  windows-test:
    name: Test
    strategy:
      matrix:
        platform: [windows-latest]
        go_version: [1.14]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go ${{ matrix.go_version }} on ${{ matrix.platform }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Install packages
        run: |
          choco install sqlite

      - name: Install aws-cli
        uses: chrislennon/action-aws-cli@v1.1

      - name: Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          go env GOPATH
          export PATH=/c/Users/runneradmin/go/bin:$PATH
          echo $PATH
          make ci_windows
        shell: bash
        env:
          DEBUG: "true"
          GOPROXY: "https://proxy.golang.org"
