name: release

on:
  push:

jobs:
  windows-release:
    name: Release assets for Windows
    strategy:
      matrix:
        go_version: [1.17]
    runs-on: windows-latest
    steps:
      - name: Set up Go ${{ matrix.go_version }} on ${{ matrix.platform }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Install packages
        run: |
          choco install sqlite

      - name: Install aws-cli
        uses: isbang/setup-awscli@v0.1.0

      - name: Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          make ci_windows
        shell: bash
        env:
          DEBUG: "true"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: --config .goreleaser/windows.yml --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: ls -la dist/
        shell: bash
